USE GestionRadioERP;
GO

IF OBJECT_ID('dbo.GR_PROGRAMACION', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.GR_PROGRAMACION;
END
GO

CREATE TABLE dbo.GR_PROGRAMACION
(
    ID_PROGRAMACION       BIGINT IDENTITY(1,1) NOT NULL,

    ID_CAMPANIA           BIGINT NOT NULL,
    ID_VERSION            BIGINT NOT NULL,
    ID_EMISORA            BIGINT NOT NULL,

    FECHA_PROGRAMACION    DATE NOT NULL,
    HORA_PROGRAMADA       TIME(0) NOT NULL,

    MATERIAL_ID_DINESAT   BIGINT NOT NULL,
    CODIGO_MATERIAL       NVARCHAR(30) NOT NULL,
    TITULO_MATERIAL       NVARCHAR(250) NOT NULL,
    DURACION_SEGUNDOS     INT NOT NULL,

    ORDEN                 INT NOT NULL,

    TRANSMITIDO           BIT NOT NULL
        CONSTRAINT DF_GR_PROGRAMACION_TRANSMITIDO DEFAULT(0),

    ACTIVO                BIT NOT NULL
        CONSTRAINT DF_GR_PROGRAMACION_ACTIVO DEFAULT(1),

    FECHA_ALTA            DATETIME2 NOT NULL
        CONSTRAINT DF_GR_PROGRAMACION_FECHA_ALTA DEFAULT(SYSDATETIME()),

    USUARIO_ALTA          NVARCHAR(100) NOT NULL,

    FECHA_MODIFICACION    DATETIME2 NULL,

    USUARIO_MODIFICACION  NVARCHAR(100) NULL,

    CONSTRAINT PK_GR_PROGRAMACION
        PRIMARY KEY (ID_PROGRAMACION)
);
GO

CREATE INDEX IX_GR_PROGRAMACION_FECHA
ON dbo.GR_PROGRAMACION(FECHA_PROGRAMACION);
GO

CREATE INDEX IX_GR_PROGRAMACION_VERSION
ON dbo.GR_PROGRAMACION(ID_VERSION);
GO

CREATE INDEX IX_GR_PROGRAMACION_CAMPANIA
ON dbo.GR_PROGRAMACION(ID_CAMPANIA);
GO

ALTER TABLE dbo.GR_PROGRAMACION
ADD CONSTRAINT FK_GR_PROGRAMACION_CAMPANIA
FOREIGN KEY(ID_CAMPANIA)
REFERENCES dbo.GR_CAMPANIA(ID_CAMPANIA);
GO

ALTER TABLE dbo.GR_PROGRAMACION
ADD CONSTRAINT FK_GR_PROGRAMACION_VERSION
FOREIGN KEY(ID_VERSION)
REFERENCES dbo.GR_VERSION(ID_VERSION);
GO