/*==============================================================================
    GESTIÓN RADIO
    SPRINT 7.1
    MOTOR DE PLANTILLAS MAESTRAS

    Script:
        002_001_GR_Plantillas.sql
==============================================================================*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/*==============================================================================
    ELIMINAR TABLAS
==============================================================================*/

IF OBJECT_ID('dbo.GR_PLANTILLA_BLOQUE_DETALLE','U') IS NOT NULL
    DROP TABLE dbo.GR_PLANTILLA_BLOQUE_DETALLE;
GO

IF OBJECT_ID('dbo.GR_PLANTILLA_BLOQUE','U') IS NOT NULL
    DROP TABLE dbo.GR_PLANTILLA_BLOQUE;
GO

IF OBJECT_ID('dbo.GR_PLANTILLA','U') IS NOT NULL
    DROP TABLE dbo.GR_PLANTILLA;
GO

/*==============================================================================
    PLANTILLA
==============================================================================*/

CREATE TABLE dbo.GR_PLANTILLA
(
    PLANTILLAID BIGINT IDENTITY(1,1) NOT NULL,
    EMISORAID BIGINT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(300) NULL,

    ACTIVA BIT NOT NULL
        CONSTRAINT DF_GR_PLANTILLA_ACTIVA DEFAULT(1),

    FECHACREACION DATETIME2 NOT NULL
        CONSTRAINT DF_GR_PLANTILLA_FECHA DEFAULT(SYSDATETIME()),

    USUARIOCREACION NVARCHAR(100) NULL,

    CONSTRAINT PK_GR_PLANTILLA
        PRIMARY KEY (PLANTILLAID)
);
GO

/*==============================================================================
    BLOQUES
==============================================================================*/

CREATE TABLE dbo.GR_PLANTILLA_BLOQUE
(
    BLOQUEID BIGINT IDENTITY(1,1) NOT NULL,

    PLANTILLAID BIGINT NOT NULL,

    ORDEN INT NOT NULL,

    HORA TIME(0) NOT NULL,

    TIPOEVENTOID BIGINT NOT NULL,

    PROGRAMAID BIGINT NULL,

    DESCRIPCION NVARCHAR(250) NULL,

    DURACIONMAXIMASEGUNDOS INT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_DURACION DEFAULT(0),

    PERMITEPUBLICIDAD BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_PUBLICIDAD DEFAULT(0),

    ESOBLIGATORIO BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_OBLIGATORIO DEFAULT(0),

    PRIORIDAD INT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_PRIORIDAD DEFAULT(100),

    DIASSEMANA TINYINT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_DIAS DEFAULT(127),

    COMPORTAMIENTO TINYINT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_COMPORTAMIENTO DEFAULT(1),

    EDITABLE BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_EDITABLE DEFAULT(1),

    ACTIVO BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUE_ACTIVO DEFAULT(1),

    CONSTRAINT PK_GR_PLANTILLA_BLOQUE
        PRIMARY KEY (BLOQUEID),

    CONSTRAINT FK_GR_PLANTILLA_BLOQUE
        FOREIGN KEY (PLANTILLAID)
        REFERENCES dbo.GR_PLANTILLA(PLANTILLAID)
);
GO

/*==============================================================================
    DETALLE DEL BLOQUE
==============================================================================*/

CREATE TABLE dbo.GR_PLANTILLA_BLOQUE_DETALLE
(
    DETALLEID BIGINT IDENTITY(1,1) NOT NULL,

    BLOQUEID BIGINT NOT NULL,

    ORDEN INT NOT NULL,

    TIPOEVENTOID BIGINT NOT NULL,

    FUENTE TINYINT NOT NULL,

    MATERIALFIJO NVARCHAR(30) NULL,

    DURACIONMAXSEGUNDOS INT NOT NULL
        CONSTRAINT DF_GR_BLOQUEDET_DURACION DEFAULT(0),

    OBLIGATORIO BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUEDET_OBLIGATORIO DEFAULT(1),

    PRIORIDAD INT NOT NULL
        CONSTRAINT DF_GR_BLOQUEDET_PRIORIDAD DEFAULT(100),

    ACTIVO BIT NOT NULL
        CONSTRAINT DF_GR_BLOQUEDET_ACTIVO DEFAULT(1),

    CONSTRAINT PK_GR_PLANTILLA_BLOQUE_DETALLE
        PRIMARY KEY (DETALLEID),

    CONSTRAINT FK_GR_PLANTILLA_BLOQUE_DETALLE
        FOREIGN KEY (BLOQUEID)
        REFERENCES dbo.GR_PLANTILLA_BLOQUE(BLOQUEID)
);
GO

/*==============================================================================
    ÍNDICES
==============================================================================*/

CREATE INDEX IX_GR_PLANTILLA_EMISORA
ON dbo.GR_PLANTILLA(EMISORAID);
GO

CREATE INDEX IX_GR_BLOQUE_PLANTILLA
ON dbo.GR_PLANTILLA_BLOQUE
(
    PLANTILLAID,
    ORDEN
);
GO

CREATE INDEX IX_GR_BLOQUE_HORA
ON dbo.GR_PLANTILLA_BLOQUE
(
    PLANTILLAID,
    HORA
);
GO

CREATE INDEX IX_GR_BLOQUE_TIPO
ON dbo.GR_PLANTILLA_BLOQUE
(
    TIPOEVENTOID
);
GO

CREATE INDEX IX_GR_BLOQUEDET_BLOQUE
ON dbo.GR_PLANTILLA_BLOQUE_DETALLE
(
    BLOQUEID,
    ORDEN
);
GO