/*
==========================================================
GESTIÓN RADIO
Sprint 3
Módulo: VERSIONES
Script : 003_001_GR_VERSION.sql
==========================================================
*/

IF OBJECT_ID('dbo.GR_VERSION', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.GR_VERSION;
END
GO

CREATE TABLE dbo.GR_VERSION
(
    ID_VERSION                 BIGINT IDENTITY(1,1) NOT NULL,

    ID_CAMPANIA                BIGINT NOT NULL,

    MATERIAL_ID_DINESAT        BIGINT NOT NULL,

    CODIGO_MATERIAL            VARCHAR(20) NOT NULL,

    TITULO_MATERIAL            NVARCHAR(200) NOT NULL,

    DURACION_SEGUNDOS          INT NOT NULL,

    ORDEN_ROTACION             TINYINT NOT NULL
        CONSTRAINT DF_GR_VERSION_ORDEN_ROTACION DEFAULT (1),

    PREFERENTE                 BIT NOT NULL
        CONSTRAINT DF_GR_VERSION_PREFERENTE DEFAULT (0),

    ACTIVO                     BIT NOT NULL
        CONSTRAINT DF_GR_VERSION_ACTIVO DEFAULT (1),

    FECHA_ALTA                 DATETIME2 NOT NULL
        CONSTRAINT DF_GR_VERSION_FECHA_ALTA DEFAULT (SYSDATETIME()),

    USUARIO_ALTA               NVARCHAR(100) NOT NULL,

    FECHA_MODIFICACION         DATETIME2 NULL,

    USUARIO_MODIFICACION       NVARCHAR(100) NULL,

    CONSTRAINT PK_GR_VERSION
        PRIMARY KEY CLUSTERED (ID_VERSION),

    CONSTRAINT FK_GR_VERSION_CAMPANIA
        FOREIGN KEY (ID_CAMPANIA)
        REFERENCES dbo.GR_CAMPANIA(ID_CAMPANIA),

    CONSTRAINT CK_GR_VERSION_DURACION
        CHECK (DURACION_SEGUNDOS > 0),

    CONSTRAINT CK_GR_VERSION_ORDEN
        CHECK (ORDEN_ROTACION BETWEEN 1 AND 15)
);
GO

CREATE INDEX IX_GR_VERSION_CAMPANIA
ON dbo.GR_VERSION(ID_CAMPANIA);
GO

CREATE INDEX IX_GR_VERSION_MATERIAL
ON dbo.GR_VERSION(MATERIAL_ID_DINESAT);
GO

CREATE INDEX IX_GR_VERSION_ACTIVO
ON dbo.GR_VERSION(ACTIVO);
GO

PRINT 'Tabla GR_VERSION creada correctamente.';
GO