<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Dinesat\" />
    <Folder Include="Features\Clientes\DTOs\" />
    <Folder Include="Features\Clientes\Mapping\" />
    <Folder Include="Features\Clientes\Commands\" />
    <Folder Include="Features\Clientes\Validators\" />
    <Folder Include="Features\Clientes\Queries\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionRadio.Domain\GestionRadio.Domain.csproj" />
  </ItemGroup>

</Project>
