/*==============================================================
    GESTIÓN RADIO
    Script : 001_002_GR_Campania.sql
    Tabla  : GR_CAMPANIA
==============================================================*/

IF OBJECT_ID('dbo.GR_CAMPANIA', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.GR_CAMPANIA;
END
GO

CREATE TABLE dbo.GR_CAMPANIA
(
    ID_CAMPANIA BIGINT IDENTITY(1,1) NOT NULL,

    FOLIO VARCHAR(20) NOT NULL,

    ID_CLIENTE BIGINT NOT NULL,

    NOMBRE NVARCHAR(200) NOT NULL,

    DESCRIPCION NVARCHAR(500) NULL,

    FECHA_INICIO DATE NOT NULL,

    FECHA_FIN DATE NOT NULL,

    PRIORIDAD TINYINT NOT NULL
        CONSTRAINT DF_GR_CAMPANIA_PRIORIDAD
        DEFAULT (3),

    ESTADO VARCHAR(20) NOT NULL
        CONSTRAINT DF_GR_CAMPANIA_ESTADO
        DEFAULT ('BORRADOR'),

    ACTIVO BIT NOT NULL
        CONSTRAINT DF_GR_CAMPANIA_ACTIVO
        DEFAULT (1),

    FECHA_ALTA DATETIME2 NOT NULL
        CONSTRAINT DF_GR_CAMPANIA_FECHA_ALTA
        DEFAULT (GETDATE()),

    USUARIO_ALTA BIGINT NOT NULL,

    FECHA_MODIFICACION DATETIME2 NULL,

    USUARIO_MODIFICACION BIGINT NULL,

    CONSTRAINT PK_GR_CAMPANIA
        PRIMARY KEY CLUSTERED (ID_CAMPANIA),

    CONSTRAINT UQ_GR_CAMPANIA_FOLIO
        UNIQUE (FOLIO),

    CONSTRAINT FK_GR_CAMPANIA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES dbo.GR_CLIENTE(ID_CLIENTE),

    CONSTRAINT CK_GR_CAMPANIA_FECHAS
        CHECK (FECHA_FIN >= FECHA_INICIO),

    CONSTRAINT CK_GR_CAMPANIA_PRIORIDAD
        CHECK (PRIORIDAD BETWEEN 1 AND 4),

    CONSTRAINT CK_GR_CAMPANIA_ESTADO
        CHECK
        (
            ESTADO IN
            (
                'BORRADOR',
                'PROGRAMADA',
                'ACTIVA',
                'PAUSADA',
                'FINALIZADA',
                'CANCELADA'
            )
        )
);
GO

/*==============================================================
    ÍNDICES
==============================================================*/

CREATE INDEX IX_GR_CAMPANIA_CLIENTE
ON dbo.GR_CAMPANIA(ID_CLIENTE);
GO

CREATE INDEX IX_GR_CAMPANIA_ESTADO
ON dbo.GR_CAMPANIA(ESTADO);
GO

CREATE INDEX IX_GR_CAMPANIA_ACTIVO
ON dbo.GR_CAMPANIA(ACTIVO);
GO

CREATE INDEX IX_GR_CAMPANIA_FECHA_INICIO
ON dbo.GR_CAMPANIA(FECHA_INICIO);
GO

CREATE INDEX IX_GR_CAMPANIA_FECHA_FIN
ON dbo.GR_CAMPANIA(FECHA_FIN);
GO

CREATE INDEX IX_GR_CAMPANIA_FECHAS
ON dbo.GR_CAMPANIA(FECHA_INICIO, FECHA_FIN);
GO