//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.241.137.200:4903/wsdl", ConfigurationName="ServiceReference2.IHdxStationsWebService")]
    public interface IHdxStationsWebService
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Programming_GetStructure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_GetStructureResponse> Programming_GetStructureAsync(ServiceReference2.Programming_GetStructureRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Programming_GetByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_GetByDateResponse> Programming_GetByDateAsync(ServiceReference2.Programming_GetByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Programming_InsertByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_InsertByDateResponse> Programming_InsertByDateAsync(ServiceReference2.Programming_InsertByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Programming_DeleteByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_DeleteByDateResponse> Programming_DeleteByDateAsync(ServiceReference2.Programming_DeleteByDateRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Station_GetStationState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Station_GetStationStateResponse> Station_GetStationStateAsync(ServiceReference2.Station_GetStationStateRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Station_GetStationById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Station_GetStationByIdResponse> Station_GetStationByIdAsync(ServiceReference2.Station_GetStationByIdRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxStationsWebService#Station_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference2.Station_GetAllResponse> Station_GetAllAsync(ServiceReference2.Station_GetAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_GetStructure", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_GetStructureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ProgrammingStructureXML;
        
        public Programming_GetStructureRequest()
        {
        }
        
        public Programming_GetStructureRequest(string SessionId, string ProgrammingStructureXML)
        {
            this.SessionId = SessionId;
            this.ProgrammingStructureXML = ProgrammingStructureXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_GetStructureResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_GetStructureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ProgrammingStructureXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Programming_GetStructureResponse()
        {
        }
        
        public Programming_GetStructureResponse(string ProgrammingStructureXML, string @return)
        {
            this.ProgrammingStructureXML = ProgrammingStructureXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_GetByDate", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_GetByDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string PgmDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int PgmTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string UTCModifiedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string UTCModifiedTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string ProgrammingXML;
        
        public Programming_GetByDateRequest()
        {
        }
        
        public Programming_GetByDateRequest(string SessionId, string StationID, string PgmDate, int PgmTypeId, string UTCModifiedDate, string UTCModifiedTime, string ProgrammingXML)
        {
            this.SessionId = SessionId;
            this.StationID = StationID;
            this.PgmDate = PgmDate;
            this.PgmTypeId = PgmTypeId;
            this.UTCModifiedDate = UTCModifiedDate;
            this.UTCModifiedTime = UTCModifiedTime;
            this.ProgrammingXML = ProgrammingXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_GetByDateResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_GetByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UTCModifiedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UTCModifiedTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ProgrammingXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string @return;
        
        public Programming_GetByDateResponse()
        {
        }
        
        public Programming_GetByDateResponse(string UTCModifiedDate, string UTCModifiedTime, string ProgrammingXML, string @return)
        {
            this.UTCModifiedDate = UTCModifiedDate;
            this.UTCModifiedTime = UTCModifiedTime;
            this.ProgrammingXML = ProgrammingXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_InsertByDate", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_InsertByDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string PgmDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int PgmTypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ProgrammingXML;
        
        public Programming_InsertByDateRequest()
        {
        }
        
        public Programming_InsertByDateRequest(string SessionId, string StationID, string PgmDate, int PgmTypeId, string ProgrammingXML)
        {
            this.SessionId = SessionId;
            this.StationID = StationID;
            this.PgmDate = PgmDate;
            this.PgmTypeId = PgmTypeId;
            this.ProgrammingXML = ProgrammingXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_InsertByDateResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_InsertByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Programming_InsertByDateResponse()
        {
        }
        
        public Programming_InsertByDateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_DeleteByDate", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_DeleteByDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string PgmDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int PgmTypeId;
        
        public Programming_DeleteByDateRequest()
        {
        }
        
        public Programming_DeleteByDateRequest(string SessionId, string StationID, string PgmDate, int PgmTypeId)
        {
            this.SessionId = SessionId;
            this.StationID = StationID;
            this.PgmDate = PgmDate;
            this.PgmTypeId = PgmTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Programming_DeleteByDateResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Programming_DeleteByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Programming_DeleteByDateResponse()
        {
        }
        
        public Programming_DeleteByDateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetStationState", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetStationStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ActualDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ActualTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string StationStateXML;
        
        public Station_GetStationStateRequest()
        {
        }
        
        public Station_GetStationStateRequest(string SessionId, string StationId, string ActualDate, string ActualTime, string StationStateXML)
        {
            this.SessionId = SessionId;
            this.StationId = StationId;
            this.ActualDate = ActualDate;
            this.ActualTime = ActualTime;
            this.StationStateXML = StationStateXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetStationStateResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetStationStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ActualDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ActualTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string StationStateXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string @return;
        
        public Station_GetStationStateResponse()
        {
        }
        
        public Station_GetStationStateResponse(string ActualDate, string ActualTime, string StationStateXML, string @return)
        {
            this.ActualDate = ActualDate;
            this.ActualTime = ActualTime;
            this.StationStateXML = StationStateXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetStationById", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetStationByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string StationXML;
        
        public Station_GetStationByIdRequest()
        {
        }
        
        public Station_GetStationByIdRequest(string SessionId, string StationId, string StationXML)
        {
            this.SessionId = SessionId;
            this.StationId = StationId;
            this.StationXML = StationXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetStationByIdResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetStationByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string StationXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Station_GetStationByIdResponse()
        {
        }
        
        public Station_GetStationByIdResponse(string StationXML, string @return)
        {
            this.StationXML = StationXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetAll", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string StationListXML;
        
        public Station_GetAllRequest()
        {
        }
        
        public Station_GetAllRequest(string SessionId, string StationListXML)
        {
            this.SessionId = SessionId;
            this.StationListXML = StationListXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Station_GetAllResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxStationsWebService", IsWrapped=true)]
    public partial class Station_GetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string StationListXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Station_GetAllResponse()
        {
        }
        
        public Station_GetAllResponse(string StationListXML, string @return)
        {
            this.StationListXML = StationListXML;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IHdxStationsWebServiceChannel : ServiceReference2.IHdxStationsWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class HdxStationsWebServiceClient : System.ServiceModel.ClientBase<ServiceReference2.IHdxStationsWebService>, ServiceReference2.IHdxStationsWebService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HdxStationsWebServiceClient() : 
                base(HdxStationsWebServiceClient.GetDefaultBinding(), HdxStationsWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IHdxStationsWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxStationsWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HdxStationsWebServiceClient.GetBindingForEndpoint(endpointConfiguration), HdxStationsWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxStationsWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HdxStationsWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxStationsWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HdxStationsWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxStationsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Programming_GetStructureResponse> Programming_GetStructureAsync(ServiceReference2.Programming_GetStructureRequest request)
        {
            return base.Channel.Programming_GetStructureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Programming_GetByDateResponse> Programming_GetByDateAsync(ServiceReference2.Programming_GetByDateRequest request)
        {
            return base.Channel.Programming_GetByDateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_InsertByDateResponse> ServiceReference2.IHdxStationsWebService.Programming_InsertByDateAsync(ServiceReference2.Programming_InsertByDateRequest request)
        {
            return base.Channel.Programming_InsertByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Programming_InsertByDateResponse> Programming_InsertByDateAsync(string SessionId, string StationID, string PgmDate, int PgmTypeId, string ProgrammingXML)
        {
            ServiceReference2.Programming_InsertByDateRequest inValue = new ServiceReference2.Programming_InsertByDateRequest();
            inValue.SessionId = SessionId;
            inValue.StationID = StationID;
            inValue.PgmDate = PgmDate;
            inValue.PgmTypeId = PgmTypeId;
            inValue.ProgrammingXML = ProgrammingXML;
            return ((ServiceReference2.IHdxStationsWebService)(this)).Programming_InsertByDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.Programming_DeleteByDateResponse> ServiceReference2.IHdxStationsWebService.Programming_DeleteByDateAsync(ServiceReference2.Programming_DeleteByDateRequest request)
        {
            return base.Channel.Programming_DeleteByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Programming_DeleteByDateResponse> Programming_DeleteByDateAsync(string SessionId, string StationID, string PgmDate, int PgmTypeId)
        {
            ServiceReference2.Programming_DeleteByDateRequest inValue = new ServiceReference2.Programming_DeleteByDateRequest();
            inValue.SessionId = SessionId;
            inValue.StationID = StationID;
            inValue.PgmDate = PgmDate;
            inValue.PgmTypeId = PgmTypeId;
            return ((ServiceReference2.IHdxStationsWebService)(this)).Programming_DeleteByDateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Station_GetStationStateResponse> Station_GetStationStateAsync(ServiceReference2.Station_GetStationStateRequest request)
        {
            return base.Channel.Station_GetStationStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Station_GetStationByIdResponse> Station_GetStationByIdAsync(ServiceReference2.Station_GetStationByIdRequest request)
        {
            return base.Channel.Station_GetStationByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Station_GetAllResponse> Station_GetAllAsync(ServiceReference2.Station_GetAllRequest request)
        {
            return base.Channel.Station_GetAllAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IHdxStationsWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IHdxStationsWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:4903/soap/IHdxStationsWebService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HdxStationsWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.IHdxStationsWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HdxStationsWebServiceClient.GetEndpointAddress(EndpointConfiguration.IHdxStationsWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IHdxStationsWebServicePort,
        }
    }
}
