//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.241.137.200:4903/wsdl", ConfigurationName="ServiceReference1.IHdxSoapWebService")]
    public interface IHdxSoapWebService
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_LogIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_LogInResponse> Server_LogInAsync(ServiceReference1.Server_LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_LogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_LogOutResponse> Server_LogOutAsync(ServiceReference1.Server_LogOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_AliveMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_AliveMessageResponse> Server_AliveMessageAsync(ServiceReference1.Server_AliveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_SleepMSec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_SleepMSecResponse> Server_SleepMSecAsync(ServiceReference1.Server_SleepMSecRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_GetDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_GetDateTimeResponse> Server_GetDateTimeAsync(ServiceReference1.Server_GetDateTimeRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_GetVersionResponse> Server_GetVersionAsync(ServiceReference1.Server_GetVersionRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_GetId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_GetIdResponse> Server_GetIdAsync(ServiceReference1.Server_GetIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_SendHdxMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_SendHdxMessageResponse> Server_SendHdxMessageAsync(ServiceReference1.Server_SendHdxMessageRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_ReceiveHdxMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_ReceiveHdxMessageResponse> Server_ReceiveHdxMessageAsync(ServiceReference1.Server_ReceiveHdxMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_ClearHdxMessageQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_ClearHdxMessageQueueResponse> Server_ClearHdxMessageQueueAsync(ServiceReference1.Server_ClearHdxMessageQueueRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#RemoteControl_GetWorkstations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.RemoteControl_GetWorkstationsResponse> RemoteControl_GetWorkstationsAsync(ServiceReference1.RemoteControl_GetWorkstationsRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_GetWeatherInfoById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_GetWeatherInfoByIdResponse> Server_GetWeatherInfoByIdAsync(ServiceReference1.Server_GetWeatherInfoByIdRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HdxSoapWebServiceIntf-IHdxSoapWebService#Server_GetWeatherCities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.Server_GetWeatherCitiesResponse> Server_GetWeatherCitiesAsync(ServiceReference1.Server_GetWeatherCitiesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_LogIn", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_LogInRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string HandledHdxMessagesXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string SessionId;
        
        public Server_LogInRequest()
        {
        }
        
        public Server_LogInRequest(string UserName, string Password, string HandledHdxMessagesXML, string SessionId)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.HandledHdxMessagesXML = HandledHdxMessagesXML;
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_LogInResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_LogInResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Server_LogInResponse()
        {
        }
        
        public Server_LogInResponse(string SessionId, string @return)
        {
            this.SessionId = SessionId;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_LogOut", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_LogOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        public Server_LogOutRequest()
        {
        }
        
        public Server_LogOutRequest(string SessionId)
        {
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_LogOutResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_LogOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Server_LogOutResponse()
        {
        }
        
        public Server_LogOutResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_AliveMessage", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_AliveMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        public Server_AliveMessageRequest()
        {
        }
        
        public Server_AliveMessageRequest(string SessionId)
        {
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_AliveMessageResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_AliveMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Server_AliveMessageResponse()
        {
        }
        
        public Server_AliveMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_SleepMSec", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_SleepMSecRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int MSec;
        
        public Server_SleepMSecRequest()
        {
        }
        
        public Server_SleepMSecRequest(string SessionId, int MSec)
        {
            this.SessionId = SessionId;
            this.MSec = MSec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_SleepMSecResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_SleepMSecResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Server_SleepMSecResponse()
        {
        }
        
        public Server_SleepMSecResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetDateTime", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetDateTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string DateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string UTCDateTime;
        
        public Server_GetDateTimeRequest()
        {
        }
        
        public Server_GetDateTimeRequest(string SessionId, string DateTime, string UTCDateTime)
        {
            this.SessionId = SessionId;
            this.DateTime = DateTime;
            this.UTCDateTime = UTCDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetDateTimeResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetDateTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UTCDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @return;
        
        public Server_GetDateTimeResponse()
        {
        }
        
        public Server_GetDateTimeResponse(string DateTime, string UTCDateTime, string @return)
        {
            this.DateTime = DateTime;
            this.UTCDateTime = UTCDateTime;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetVersion", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Version;
        
        public Server_GetVersionRequest()
        {
        }
        
        public Server_GetVersionRequest(string SessionId, string Version)
        {
            this.SessionId = SessionId;
            this.Version = Version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetVersionResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Server_GetVersionResponse()
        {
        }
        
        public Server_GetVersionResponse(string Version, string @return)
        {
            this.Version = Version;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetId", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ServerId;
        
        public Server_GetIdRequest()
        {
        }
        
        public Server_GetIdRequest(string SessionId, string ServerId)
        {
            this.SessionId = SessionId;
            this.ServerId = ServerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetIdResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ServerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Server_GetIdResponse()
        {
        }
        
        public Server_GetIdResponse(string ServerId, string @return)
        {
            this.ServerId = ServerId;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_SendHdxMessage", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_SendHdxMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string MsgId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ParamsXML;
        
        public Server_SendHdxMessageRequest()
        {
        }
        
        public Server_SendHdxMessageRequest(string SessionId, string MsgId, string ParamsXML)
        {
            this.SessionId = SessionId;
            this.MsgId = MsgId;
            this.ParamsXML = ParamsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_SendHdxMessageResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_SendHdxMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Server_SendHdxMessageResponse()
        {
        }
        
        public Server_SendHdxMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_ReceiveHdxMessage", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_ReceiveHdxMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string MsgId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ParamsXML;
        
        public Server_ReceiveHdxMessageRequest()
        {
        }
        
        public Server_ReceiveHdxMessageRequest(string SessionId, string MsgId, string ParamsXML)
        {
            this.SessionId = SessionId;
            this.MsgId = MsgId;
            this.ParamsXML = ParamsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_ReceiveHdxMessageResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_ReceiveHdxMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string MsgId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ParamsXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @return;
        
        public Server_ReceiveHdxMessageResponse()
        {
        }
        
        public Server_ReceiveHdxMessageResponse(string MsgId, string ParamsXML, string @return)
        {
            this.MsgId = MsgId;
            this.ParamsXML = ParamsXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_ClearHdxMessageQueue", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_ClearHdxMessageQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        public Server_ClearHdxMessageQueueRequest()
        {
        }
        
        public Server_ClearHdxMessageQueueRequest(string SessionId)
        {
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_ClearHdxMessageQueueResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_ClearHdxMessageQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Server_ClearHdxMessageQueueResponse()
        {
        }
        
        public Server_ClearHdxMessageQueueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteControl_GetWorkstations", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class RemoteControl_GetWorkstationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RemoteWorkstationsXML;
        
        public RemoteControl_GetWorkstationsRequest()
        {
        }
        
        public RemoteControl_GetWorkstationsRequest(string SessionId, string RemoteWorkstationsXML)
        {
            this.SessionId = SessionId;
            this.RemoteWorkstationsXML = RemoteWorkstationsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteControl_GetWorkstationsResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class RemoteControl_GetWorkstationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RemoteWorkstationsXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public RemoteControl_GetWorkstationsResponse()
        {
        }
        
        public RemoteControl_GetWorkstationsResponse(string RemoteWorkstationsXML, string @return)
        {
            this.RemoteWorkstationsXML = RemoteWorkstationsXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetWeatherInfoById", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetWeatherInfoByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string WeatherInfoXML;
        
        public Server_GetWeatherInfoByIdRequest()
        {
        }
        
        public Server_GetWeatherInfoByIdRequest(string SessionId, string CityId, string WeatherInfoXML)
        {
            this.SessionId = SessionId;
            this.CityId = CityId;
            this.WeatherInfoXML = WeatherInfoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetWeatherInfoByIdResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetWeatherInfoByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WeatherInfoXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Server_GetWeatherInfoByIdResponse()
        {
        }
        
        public Server_GetWeatherInfoByIdResponse(string WeatherInfoXML, string @return)
        {
            this.WeatherInfoXML = WeatherInfoXML;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetWeatherCities", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetWeatherCitiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CitiesInfoXML;
        
        public Server_GetWeatherCitiesRequest()
        {
        }
        
        public Server_GetWeatherCitiesRequest(string SessionId, string CitiesInfoXML)
        {
            this.SessionId = SessionId;
            this.CitiesInfoXML = CitiesInfoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Server_GetWeatherCitiesResponse", WrapperNamespace="urn:HdxSoapWebServiceIntf-IHdxSoapWebService", IsWrapped=true)]
    public partial class Server_GetWeatherCitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CitiesInfoXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @return;
        
        public Server_GetWeatherCitiesResponse()
        {
        }
        
        public Server_GetWeatherCitiesResponse(string CitiesInfoXML, string @return)
        {
            this.CitiesInfoXML = CitiesInfoXML;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IHdxSoapWebServiceChannel : ServiceReference1.IHdxSoapWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class HdxSoapWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IHdxSoapWebService>, ServiceReference1.IHdxSoapWebService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HdxSoapWebServiceClient() : 
                base(HdxSoapWebServiceClient.GetDefaultBinding(), HdxSoapWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IHdxSoapWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxSoapWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HdxSoapWebServiceClient.GetBindingForEndpoint(endpointConfiguration), HdxSoapWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxSoapWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HdxSoapWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxSoapWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HdxSoapWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HdxSoapWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_LogInResponse> Server_LogInAsync(ServiceReference1.Server_LogInRequest request)
        {
            return base.Channel.Server_LogInAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Server_LogOutResponse> ServiceReference1.IHdxSoapWebService.Server_LogOutAsync(ServiceReference1.Server_LogOutRequest request)
        {
            return base.Channel.Server_LogOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_LogOutResponse> Server_LogOutAsync(string SessionId)
        {
            ServiceReference1.Server_LogOutRequest inValue = new ServiceReference1.Server_LogOutRequest();
            inValue.SessionId = SessionId;
            return ((ServiceReference1.IHdxSoapWebService)(this)).Server_LogOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Server_AliveMessageResponse> ServiceReference1.IHdxSoapWebService.Server_AliveMessageAsync(ServiceReference1.Server_AliveMessageRequest request)
        {
            return base.Channel.Server_AliveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_AliveMessageResponse> Server_AliveMessageAsync(string SessionId)
        {
            ServiceReference1.Server_AliveMessageRequest inValue = new ServiceReference1.Server_AliveMessageRequest();
            inValue.SessionId = SessionId;
            return ((ServiceReference1.IHdxSoapWebService)(this)).Server_AliveMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Server_SleepMSecResponse> ServiceReference1.IHdxSoapWebService.Server_SleepMSecAsync(ServiceReference1.Server_SleepMSecRequest request)
        {
            return base.Channel.Server_SleepMSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_SleepMSecResponse> Server_SleepMSecAsync(string SessionId, int MSec)
        {
            ServiceReference1.Server_SleepMSecRequest inValue = new ServiceReference1.Server_SleepMSecRequest();
            inValue.SessionId = SessionId;
            inValue.MSec = MSec;
            return ((ServiceReference1.IHdxSoapWebService)(this)).Server_SleepMSecAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_GetDateTimeResponse> Server_GetDateTimeAsync(ServiceReference1.Server_GetDateTimeRequest request)
        {
            return base.Channel.Server_GetDateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_GetVersionResponse> Server_GetVersionAsync(ServiceReference1.Server_GetVersionRequest request)
        {
            return base.Channel.Server_GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_GetIdResponse> Server_GetIdAsync(ServiceReference1.Server_GetIdRequest request)
        {
            return base.Channel.Server_GetIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Server_SendHdxMessageResponse> ServiceReference1.IHdxSoapWebService.Server_SendHdxMessageAsync(ServiceReference1.Server_SendHdxMessageRequest request)
        {
            return base.Channel.Server_SendHdxMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_SendHdxMessageResponse> Server_SendHdxMessageAsync(string SessionId, string MsgId, string ParamsXML)
        {
            ServiceReference1.Server_SendHdxMessageRequest inValue = new ServiceReference1.Server_SendHdxMessageRequest();
            inValue.SessionId = SessionId;
            inValue.MsgId = MsgId;
            inValue.ParamsXML = ParamsXML;
            return ((ServiceReference1.IHdxSoapWebService)(this)).Server_SendHdxMessageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_ReceiveHdxMessageResponse> Server_ReceiveHdxMessageAsync(ServiceReference1.Server_ReceiveHdxMessageRequest request)
        {
            return base.Channel.Server_ReceiveHdxMessageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Server_ClearHdxMessageQueueResponse> ServiceReference1.IHdxSoapWebService.Server_ClearHdxMessageQueueAsync(ServiceReference1.Server_ClearHdxMessageQueueRequest request)
        {
            return base.Channel.Server_ClearHdxMessageQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_ClearHdxMessageQueueResponse> Server_ClearHdxMessageQueueAsync(string SessionId)
        {
            ServiceReference1.Server_ClearHdxMessageQueueRequest inValue = new ServiceReference1.Server_ClearHdxMessageQueueRequest();
            inValue.SessionId = SessionId;
            return ((ServiceReference1.IHdxSoapWebService)(this)).Server_ClearHdxMessageQueueAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemoteControl_GetWorkstationsResponse> RemoteControl_GetWorkstationsAsync(ServiceReference1.RemoteControl_GetWorkstationsRequest request)
        {
            return base.Channel.RemoteControl_GetWorkstationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_GetWeatherInfoByIdResponse> Server_GetWeatherInfoByIdAsync(ServiceReference1.Server_GetWeatherInfoByIdRequest request)
        {
            return base.Channel.Server_GetWeatherInfoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Server_GetWeatherCitiesResponse> Server_GetWeatherCitiesAsync(ServiceReference1.Server_GetWeatherCitiesRequest request)
        {
            return base.Channel.Server_GetWeatherCitiesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IHdxSoapWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IHdxSoapWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:4903/soap/IHdxSoapWebService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HdxSoapWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.IHdxSoapWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HdxSoapWebServiceClient.GetEndpointAddress(EndpointConfiguration.IHdxSoapWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IHdxSoapWebServicePort,
        }
    }
}
